version = 0.1
[default.deploy.parameters]
stack_name = "codepipeline-slack-bot"
resolve_s3 = true
s3_prefix = "codepipeline-slack-bot"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SlackChannel=\"aws_notifications\" SlackBotName=\"PipelineBuildBot\" SlackBotIcon=\":robot_face:\""
image_repositories = []
